version: '3.4'

services:
  strava-api:
    container_name: strava-api
    image: ${DOCKER_REGISTRY-}strava-api
    ports:
      - "8001:80"
      - "8002:433"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=${StravaApiDbConnectionString}

      - TokenSettings__Key=${TokenKey}
      - TokenSettings__Issuer=${TokenIssuer}
      - TokenSettings__ExpiresInDays=${TokenExpiresInDays}

      - StravaSettings__BaseUrl=https://www.strava.com/api/v3/
      - StravaSettings__ClientId=${StravaClientId}
      - StravaSettings__ClientSecret=${StravaClientSecret}

      - MessageBrokerSettings__Host=amqp://rabbitmq:5672
      - MessageBrokerSettings__Username=${RabbitMQUsername}
      - MessageBrokerSettings__Password=${RabbitMQPassword}
    build:
      context: .
      dockerfile: src/Services/Strava/Strava.Api/Dockerfile
    depends_on:
      - db_server
      - rabbitmq 


  athletes-api:
    container_name: athletes-api
    image: ${DOCKER_REGISTRY-}athletes-api
    ports:
      - "8003:80"
      - "8004:433"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=${AthletesApiDbConnectionString}

      - MessageBrokerSettings__Host=amqp://rabbitmq:5672
      - MessageBrokerSettings__Username=${RabbitMQUsername}
      - MessageBrokerSettings__Password=${RabbitMQPassword}
    build:
      context: .
      dockerfile: src/Services/Athletes/Athletes.Api/Dockerfile
    depends_on:
      - db_server
      - rabbitmq


  activities-api:
    container_name: activities-api
    image: ${DOCKER_REGISTRY-}activities-api
    ports:
      - "8005:80"
      - "8006:433"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=${ActivitiesApiDbConnectionString}

      - MessageBrokerSettings__Host=amqp://rabbitmq:5672
      - MessageBrokerSettings__Username=${RabbitMQUsername}
      - MessageBrokerSettings__Password=${RabbitMQPassword}
    build:
      context: .
      dockerfile: src/Services/Activities/Activities.Api/Dockerfile
    depends_on:
      - db_server
      - rabbitmq


  db_server:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DbPassword}


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RabbitMQUsername}
      - RABBITMQ_DEFAULT_PASS=${RabbitMQPassword}
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq