// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Strava.Infrastructure.Persistence;

#nullable disable

namespace Strava.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20241024102828_Add delete-activity-saga model")]
    partial class Adddeleteactivitysagamodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.MessageBroker.Saga.DeleteActivity.DeleteActivitySagaData", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AchievementsServiceProcessed")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivitiesServiceProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StravaActivityId")
                        .HasColumnType("bigint");

                    b.Property<long>("StravaUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TilesServiceProcessed")
                        .HasColumnType("bit");

                    b.HasKey("CorrelationId");

                    b.ToTable("DeleteActivitySagaDatas");
                });

            modelBuilder.Entity("Common.MessageBroker.Saga.ProcessActivityData.ProcessActivitySagaData", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AchievementsServiceProcessed")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivitiesServiceProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StravaActivityId")
                        .HasColumnType("bigint");

                    b.Property<long>("StravaUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TilesServiceProcessed")
                        .HasColumnType("bit");

                    b.HasKey("CorrelationId");

                    b.ToTable("ProcessActivitySagaDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
